---

- name: managing error handling with handlers
  hosts: servers
  become: True
  gather_facts: False
  vars:
    will_fail: True
  tasks:
    - name: install packages or fail
      block:

        # a mock of a successful task that will trigger a handler
        - debug:
            msg: this task is successful
          changed_when: yes
          notify:
            - show notification
        
        # force the block to fail
        - command: /bin/false
          when: will_fail
      always:
        - debug:
            msg: "[ALWAYS] This will run after succesfull/failed block"
      rescue:
        - name: a warming message
          debug:
            msg: "[RESCUE] This will run in event of a failure"
        
        # allows us to run handlers even if the block failed
        # and more importantly it will be run here
        - name: Forcing handlers
          meta: flush_handlers
      
    - debug:
        msg: "last message"
  handlers:
    - name: show notification
      debug:
        msg: "$$$$$ NOTIFICATION $$$$$"


